import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { getToken } from "./_lib/token";
import Leftsidebar from "./_components/Leftsidebar";
import Navbar from "./_components/Navbar";
import { Bounce, Slide, ToastContainer } from 'react-toastify';

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {

  const session = await getToken()

  return (
    <html lang="en">
      <body>
        <div className="min-h-screen bg-gray-50">
          <Navbar />
          <div className="flex flex-row">
            {session &&
              <div className="container ml-auto mt-10 ms-10 w-1/4 text-center">
                <Leftsidebar />
              </div>}
            <main className="container mx-auto  px-4 py-8 ">
                {children}
            </main>
          </div>
        </div>
         <ToastContainer
              transition={Slide}
              position="top-center"
              autoClose={5000}
              hideProgressBar={true}
              newestOnTop={false}
              closeOnClick={false}
              rtl={false}
              pauseOnFocusLoss
              draggable
              pauseOnHover
              theme="dark"
            />
      </body>
    </html>
  );
}
